spring:
  cloud:
    config:
      enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: eureka-server

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/api/v1/payment/pay

  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/api/v1/order/save
